# -*- coding: utf-8 -*-
"""Capstone_visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1niPs0gAE_RRzta0RquxNg4zQ24SfUfYK

# Part 1: Data Wrangling
"""

#Load Dataset and appropriate libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_csv('/content/StudentPerformanceFactors.csv')

# Inspect data
df.head()
df.info()
df.isnull().sum()

#drop NA
df.dropna(inplace=True)

df.isnull().sum()

# rename columns for further information
df = df.rename(columns={'Hours_Studied':'Hours_Studied_Per_Week',
                        'Attendance': 'Attendance_Percentage',
                        'Sleep_Hours':'Avg_Hrs_Sleep_Per_day',
                        'Physical_Activity':'Number_of_Exercise_Sessions_Per_Week',
                        'Distance_From_Home':'Distance_From_School'
                        })
df.head()
df.info()

# save new dataset to csv
df.to_csv('cleaned_data.csv', index=False)

"""# Part 2: Visualization Creation"""

# Visualization 1: Scatter Plot- Exam Score vs. Hours Studied (colored by average attendance)
'''
Code explanation:
This code uses seaborn to create a scatter plot of exam scores vs. hours studied per week. The hue was chosen  a gradient to depict
the relationship between the number of tutoring sessions and exam scores.
'''
plt.figure(figsize=(10, 6))
scatter= sns.scatterplot(data=df, x='Attendance_Percentage', y='Exam_Score', hue='Tutoring_Sessions', palette='flare')
scatter.set_title('Exam Score vs. Attendance (%) plot (colored by number of tutoring sessions)')
scatter.set_xlabel('Attendance (%)')
scatter.set_ylabel('Exam Score')
scatter.legend(title='Tutoring sessions', bbox_to_anchor=(1.05, 1), loc='upper left')
scatter.grid(alpha=0.4)
plt.show()

# Visualization 2: Box Plot- Exam Scores vs Parental Involvement
'''
Code explanation:
This code uses seaborn to create a box plot of exam scores vs. parental involvement to examine the distribution of
exam scores given different levels of parental involvement. Each level of parental involvement is represented by a different color to make differentiation easier.
'''
plt.figure(figsize=(10, 6))
box= sns.boxplot(data=df, x='Parental_Involvement', y='Exam_Score',palette='tab10',hue='Parental_Involvement')
box.set_title('Exam Scores vs Parental Involvement box plot')
box.set_xlabel('Parental Involvement')
box.set_ylabel('Exam Score (%)')
box.grid(alpha=0.4)
plt.show()

# Visualization 3: Histogram - Distribution of Exam Scores
'''
Code explanation:
This code uses matplotlib to create a histogram of exam scores to visualize the distribution of scores in the dataset. With 40 buckets, the ranges of
scores are more narrow, and the distribution is more concentrated.
'''
plt.figure(figsize=(10, 6))
hist=plt.hist(df['Exam_Score'], bins=40, color='pink', edgecolor='black')
plt.title('Distribution of Exam Scores')
plt.xlabel('Exam Score (%)')
plt.ylabel('Frequency')
plt.grid(alpha=0.4)
plt.show()

# Visualization 4: Facet Plot- Study Hours Vs Exam Score by Motivation level
'''
Code explanantion:
This code utilizes seaborn to create a facet plot based on different motivation levels of students. It graphs exam score vs hours studied that week
by the student. The hue of the plot is the average hours of sleep a student gets per day.
'''
plt.figure(figsize=(10, 6))
facet=sns.FacetGrid(data=df,col='Motivation_Level',col_wrap=3,height=4,hue='Avg_Hrs_Sleep_Per_day',palette='viridis')
facet.map(plt.scatter,'Hours_Studied_Per_Week','Exam_Score',alpha=0.5)
facet.set_axis_labels('Hours Studied per Week','Exam Score (%)')
facet.fig.suptitle('Study Hours Vs Exam Score by Motivation level', y=1.05)
facet.add_legend(title='Average Hours of Sleep per Day', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# Visualization 5: Bar graph- Exam Score vs Teacher Quality
'''
Code Explanation:
This code utilizes the bar graph from seaborn to visualize the relationship between average exam scores and based on teacher quality. The exam scores are gouped
by teacher quality and then the average exam score is calculated.
'''
plt.figure(figsize=(10, 6))
bar=sns.barplot(data=df, x='Teacher_Quality', y='Exam_Score', palette='viridis')
avg_exam_score_by_teacher_quality = df.groupby('Teacher_Quality')['Exam_Score'].mean()
bar.set_title('Exam Score vs Teacher Quality')
bar.set_xlabel('Teacher Quality')
bar.set_ylabel('Exam Score (%)')
bar.grid(alpha=0.4)
plt.show()

# Visualization 6 - Heatmap (correlation matrix)
'''
This code uses the heatmap from seaborn to visualize the correlation matrix of the numerical variables in the dataset. The numerical attributes
are seperated frm the categorical attributes, and the correlation matrix is calculated. The palette crest is chosen to highlight any strong positive or negative
correlations.
'''
num_cols=['Hours_Studied_Per_Week','Attendance_Percentage','Avg_Hrs_Sleep_Per_day','Previous_Scores','Tutoring_Sessions','Number_of_Exercise_Sessions_Per_Week','Exam_Score']
plt.figure(figsize=(10, 6))
corr_matrix=df[num_cols].corr()
heat=sns.heatmap(corr_matrix, annot=True, cmap='crest', linewidths=0.5)
heat.set_title('Correlation Heatmap of Student Performance (Numerical Variables)')
plt.show()

# save notebook to pdf